### PR TITLE
logging the session state

### PR DESCRIPTION
**Pull request by redhatHameed**
Signed-off-by: Abdul Hameed <ahameed@redhat.com>

### CODE REVIEW

**Comment by redhatHameed** [comment]
@wilybrace QE faced issue again.  I believe this issue happened in `func (c *Client) precheck() `  what you think if we can add  `c.GetLoginState() == LoginInactive`  refresh login state if inactive Let me know if that make sense.

**Comment by wilybrace** [comment]
What do you believe adding that change will do? Are you seeing log entries that show it is finding a nil session?

If they were able to run into it again, do you have a means to repeatably get into that state to validate a fix?

**Comment by redhatHameed** [comment]
> 

> What do you believe adding that change will do? Are you seeing log entries that show it is finding a nil session?

I haven't seen nil session in logs make sense I will close the PR. I was thinking this error return from LoginInactive so added checks [c.GetLoginState().toError()](https://github.com/CrunchyData/crunchy-bridge-operator/blob/2015b40feb07e32095e88223db81b34c318af30e/internal/bridgeapi/client.go#L115) for refreshing, but doesn't make sense.

> If they were able to run into it again, do you have a means to repeatably get into that state to validate a fix?
I thought we are getting an error 

Right we are getting error -> LoginInactive-> Failed to establish renewed login. 

can add logs, to print the state GetLoginState WDYT?

**Comment by redhatHameed** [comment]
@wilybrace reverted the change and added logger for the session state.

**Comment by wilybrace** [comment]
You're welcome to do instrumenting somewhere useful in a development build, but again, I think being able to reproduce the problem is needed. The log statement you've added is going to be noisy and doesn't reveal any new information. The state is directly translated into the error returned during the precheck, it's known to be invalid.

I put up a commit that ventures one guess as to the potential cause, but I need to have `rc.1` cut without debug code.

**Pull request closed without merging**
