### PR TITLE
stop reconciliation if any authentication error from API client

### PR DESCRIPTION
**Pull request by redhatHameed**
stop reconciliation if any authentication error from API client

Signed-off-by: Abdul Hameed <ahameed@redhat.com>

### CODE REVIEW

**Comment by redhatHameed** [comment]
@wilybrace open the PR to stopped the reconciliation if invalid credentials were provided. I saw the operator continue to reconciled and generate the logs

**Comment by wilybrace** [comment]
Does it make more sense to limit suppression only to `err == bridgeapi.ErrorInvalidCreds`? The other error conditions are more temporal.
Also, doesn't the manager have a backoff in the case of persistent error? If not, you could manage it through the result returned to slow the retries for invalid credentials.

It seems overkill to end reconciliation entirely for something that may eventually be corrected. It is also arguably incorrect behavior to put reconciliation into a state that is "in sync" between spec and reality when it's really (now persistently) stuck in an error condition.

**Comment by redhatHameed** [comment]
> Does it make more sense to limit suppression only to `err == bridgeapi.ErrorInvalidCreds`? The other error conditions are more temporal.
> Also, doesn't the manager have a backoff in the case of persistent error? If not, you could manage it through the result returned to slow the retries for invalid credentials.

it has default rate limit I believe this the function -> https://github.com/kubernetes/client-go/blob/911ef75/util/workqueue/default_rate_limiters.go#L39

> 
> It seems overkill to end reconciliation entirely for something that may eventually be corrected. It is also arguably incorrect behavior to put reconciliation into a state that is "in sync" between spec and reality when it's really (now persistently) stuck in an error condition.

I agreed within some cases we need to reconciliation again like secrets not created or created with invalidate credentials and corrected. Agreed to close the PR, and keep it as it is, we can revisit this if this retry making noises on the API side.

**Comment by wilybrace** [comment]
Did I remember seeing that some of the noise is the Zap logger generating panics when the reconcile returned an error? Addressing that would likely reduce a large portion of the noise.

**Comment by redhatHameed** [comment]
> Did I remember seeing that some of the noise is the Zap logger generating panics when the reconcile returned an error? Addressing that would likely reduce a large portion of the noise.

Was trying to reproduce but can't find exactly where the zap logger generate the panic,  I can see the proper error trace https://gist.github.com/redhatHameed/c587e77351a261c07c84817f04de1ae0

**Comment by wilybrace** [comment]
It appears I misinterpreted a highly verbose error trace for a stacktrace/panic. Nevermind.

**Pull request closed without merging**
