### PR TITLE
Login error management

### PR DESCRIPTION
**Pull request by wilybrace**
* removes unnecessary error return from SetLogin
* adds state tracking for login manager

### CODE REVIEW

**Review by redhatHameed — COMMENTED** [review]
@wilybrace thanks, added few comments.

**Comment by wilybrace** [comment]
@redhatHameed 
I must reemphasize that the client library, via the login manager, expects to be decorated with a working credential provider. Given its asynchronous nature, a direct error path originating from the login manager is prone to issues. 
`SetLogin` does not and did not trigger a login event, it merely updates the source of credentials for the login manager; it never returned an error and would not going forward.

Given the discussion, I have extended the `CredentialProvider` interface to provide an error alongside the `LoginCred`. It does not make sense to be a part of that type. In doing so, there's an opportunity to check the validity of the `CredentialProvider` before relying on it to provide the credentials to the login manager. The error return gives less ambiguity between a zero-value credential and an error occurring when retrieving one from another source. 

I have updated the `KubeSecretCredentialProvider` initialization in the inventory controller to do a check for the error return and for zero value as error conditions in its operation - hopefully this addresses the visibility concerns you have. Beyond validating the `CredentialProvider` creation, the client's login state can be inspected via `GetLoginState` and calls to data functions return errors if the `LoginState` is not active during the prechecks run prior to executing the API calls.

Please let me know if you have remaining concerns.

**Comment by redhatHameed** [comment]
> @redhatHameed
> I must reemphasize that the client library, via the login manager, expects to be decorated with a working credential provider. Given its asynchronous nature, a direct error path originating from the login manager is prone to issues.
> `SetLogin` does not and did not trigger a login event, it merely updates the source of credentials for the login manager; it never returned an error and would not going forward.
> 
> Given the discussion, I have extended the `CredentialProvider` interface to provide an error alongside the `LoginCred`. It does not make sense to be a part of that type. In doing so, there's an additional opportunity to check the validity of the `CredentialProvider` before relying on it to provide the credentials to the login manager. The additional error return reduces ambiguity between a zero-value credential and an error occurring when retrieving one from another source.

make sense. Thanks

> 
> I have updated the `KubeSecretCredentialProvider` initialization in the inventory controller to do a check for the error return and for zero value as error conditions in its operation - hopefully this addresses the visibility concerns you have. Beyond validating the `CredentialProvider` creation, the client's login state can be inspected via `GetLoginState` and calls to data functions return errors if the `LoginState` is not active during the prechecks run prior to executing the API calls.

sounds good to me. 
> Please let me know if you have any remaining concerns.

during my testing I found, issue in updating the secret, 

for example created the inventory cr, before creating a secret. it gives me a valid error, which is totally fine

Screen Shot 2021-08-09 at 10 37 24 AM

in the second step I have created a secret, but still getting the same error, while I saw the operator is reconciling. Any thoughts ?
Screen Shot 2021-08-09 at 10 37 24 AM

**Comment by redhatHameed** [comment]
> > @redhatHameed
> > I must reemphasize that the client library, via the login manager, expects to be decorated with a working credential provider. Given its asynchronous nature, a direct error path originating from the login manager is prone to issues.
> > `SetLogin` does not and did not trigger a login event, it merely updates the source of credentials for the login manager; it never returned an error and would not going forward.
> > Given the discussion, I have extended the `CredentialProvider` interface to provide an error alongside the `LoginCred`. It does not make sense to be a part of that type. In doing so, there's an additional opportunity to check the validity of the `CredentialProvider` before relying on it to provide the credentials to the login manager. The additional error return reduces ambiguity between a zero-value credential and an error occurring when retrieving one from another source.
> 
> make sense. Thanks
> 
> > I have updated the `KubeSecretCredentialProvider` initialization in the inventory controller to do a check for the error return and for zero value as error conditions in its operation - hopefully this addresses the visibility concerns you have. Beyond validating the `CredentialProvider` creation, the client's login state can be inspected via `GetLoginState` and calls to data functions return errors if the `LoginState` is not active during the prechecks run prior to executing the API calls.
> 
> sounds good to me.
> 
> > Please let me know if you have any remaining concerns.
> 
> during my testing I found, issue in updating the secret,
> 
> for example created the inventory cr, before creating a secret. it gives me a valid error, which is totally fine
> 
> Screen Shot 2021-08-09 at 10 37 24 AM
> 
> in the second step I have created a secret, but still getting the same error, while I saw the operator is reconciling. Any thoughts ?
> Screen Shot 2021-08-09 at 10 37 24 AM

Please ignore, it works I was referring to a different namespace. Thanks

**Review by redhatHameed — APPROVED** [review]
LGTM

**Pull request merged**
